# Generated by Django 4.2.6 on 2024-09-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0017_prospect_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='sreo_document',
            field=models.FileField(blank=True, null=True, upload_to='sreo_documents/'),
        ),
    ]
