# Generated by Django 4.2.6 on 2024-09-18 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prospect', '0018_prospect_sreo_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='SREOData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=100)),
                ('number_of_units', models.IntegerField()),
                ('acquisition_date', models.DateField()),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estimated_current_market_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('market_value_based', models.CharField(max_length=255)),
                ('lender_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('loan_number', models.CharField(max_length=100)),
                ('estimated_current_loan_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gross_monthly_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthly_loan_payment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthly_property_tax_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('average_monthly_expenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthly_cash_flow', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sreo_data_created', to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sreo_data', to='prospect.prospect')),
            ],
        ),
    ]
