# Generated by Django 4.2.6 on 2024-09-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0019_sreodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sreodata',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sreodata',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
