# Generated by Django 4.2.6 on 2024-09-18 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0020_sreodata_latitude_sreodata_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sreodata',
            options={'ordering': ['-acquisition_date', 'property_name']},
        ),
    ]
